package error

Code :: enum i32 {
	NONE = 0,
	ID_INVALID,
	OBJECT_NOT_FOUND,
	SCENE_IS_ACTIVE,
	NAME_EXISTS,
	ADDING_CAMERA_TO_ENTITY_WITH_NO_TRANSFORM,
	INVALID_CAMERA_PROJECTION,
	NO_MAIN_CAMERA_SET,
	INVALID_CAMERA
}
